# Configuration for AI Pipeline

# Input/Output paths
input_path: "/home/bht/CODE/xaip/AI_Script/inputs/videos/3.mp4"
weight_path: "/home/bht/BHT/AI/Weights/yolov5_coco2017/Yolov5s_COCO-2017_INT8_(FP32_INT32_INT64).onnx"
output_path: "/home/bht/TEST/xaip/outputs"

# Model configuration
model_name: "yolov5"
precision_format: "int8"

# Target device configuration
target:
  device: "cpu"  # Options: "cpu" or "gpu"

# Mode configuration
inference_mode: true
debug_mode: false
evaluate_mode: false

# Option configuration
tracking_option: true
