weight_path_fp32: /home/bht/CODE/xaip/AI_Script/pretrained_models/FP32/resnet50_eurosat_fp32.onnx
weight_path_fp16: /home/bht/CODE/xaip/AI_Script/pretrained_models/FP16/resnet50_eurosat_fp16.onnx
weight_path_int8: /home/bht/CODE/xaip/AI_Script/pretrained_models/INT8/resnet50_eurosat_Q0_QInt8.onnx

model_name: resnet50
task: classification
target_size: [224, 224]
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
precision_format: fp32
dataset: eurosat
default_postprocess: draw_label