weight_path_fp32: /home/bht/CODE/xaip/AI_Script/pretrained_models/FP32/yolov5s.onnx
weight_path_fp16: /home/bht/CODE/xaip/AI_Script/pretrained_models/FP16/yolov5s_fp16.onnx
weight_path_int8: /home/bht/CODE/xaip/AI_Script/pretrained_models/INT8/yolov5s_COCO_int8.onnx

# Default config
model_name: yolov5
task: object_detection
target_size: [640, 640]
mean: [0.0, 0.0, 0.0]
std: [1.0, 1.0, 1.0]
precision_format: fp32
conf_threshold: 0.3
iou_threshold: 0.5
transpose_output: False
dataset: coco
default_postprocess: draw_box